#!/usr/bin/env bash

set -x

set -e

# update packages index
# sudo dnf update -y

# Gnome config
# gsettings set org.gnome.desktop.wm.preferences focus-mode 'sloppy'
# gsettings set org.gnome.desktop.wm.preferences auto-raise true

# set hostname as Fedora doesn't give it one during installation
# hostnamectl set-hostname x1

# enable free and non-free 3rd party repos
sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

while read pkg; do
  sudo dnf -y install $pkg
done <pkgs

# vault
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
sudo dnf -y install vault

# Add key and install repository for VSCode
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
# Update dnf and install vscode
dnf check-update | true
sudo dnf -y install code

# Install snapd for installing snaps later
sudo dnf -y install snapd
sleep 5
sudo ln -sf /var/lib/snapd/snap /snap
sleep 5

# Installing Snapcraft stuff
sudo snap install authy
sudo snap install bitwarden
sudo snap install discord
sudo snap install flameshot
sudo snap install gitkraken --classic
sudo snap install google-play-music-desktop-player
sudo snap install helm --classic
sudo snap install kontena-lens --classic
sudo snap install postman
sudo snap install signal-desktop
sudo snap install slack --classic
sudo snap install simplenote
sudo snap install slack --classic # It seems snap works with Fedora KDE, yay!
sudo snap install spotify
sudo snap install zoom-client

# pip install flake8
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade pip
pip install virtualenvwrapper
pip install pgcli
# pip install kapitan


# Install Oh-My-Zsh
wget --no-check-certificate http://install.ohmyz.sh -O - | sh
# This is going to ask to change shell at end of installation so will exit then
