#!/usr/bin/env bash

set -x

set -e

# homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# https://docs.brew.sh/Homebrew-on-Linux
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile

brew tap orf/brew
brew install git-workspace

zsh -c 'brew install fzf'
$(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc
brew install jupyterlab
brew install krew
brew install kubectx
brew install derailed/k9s/k9s
brew install stern
brew install warrensbox/tap/tfswitch

# krew plugins
kubectl krew install get-all
