#!/usr/bin/env bash

set -x

set -e

# Install mega nz file syncyng stuff
source /etc/os-release

# Install minikube, should work for all linux
# https://github.com/kubernetes/minikube/releases
wget -P /tmp https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && sudo install /tmp/minikube-linux-amd64 /usr/local/bin/minikube

# Google Chrome
sudo dnf install fedora-workstation-repositories -y
sudo dnf config-manager --set-enabled google-chrome
sudo dnf install google-chrome-stable -y

# Install Keybase
sudo dnf install https://prerelease.keybase.io/keybase_amd64.rpm -y
run_keybase

# JetBrains Toolbox
# Reference: https://github.com/nagygergo/jetbrains-toolbox-install/blob/master/jetbrains-toolbox.sh
# Note that we grep for linux here, if you are using this on mac/windows please see json output
TOOLBOX_URL=$(curl --silent 'https://data.services.jetbrains.com//products/releases?code=TBA&latest=true&type=release' \
    -H 'Origin: https://www.jetbrains.com' \
    -H 'Accept-Encoding: gzip, deflate, br' \
    -H 'Accept-Language: en-US,en;q=0.8' \
    -H 'Accept: application/json, text/javascript, */*; q=0.01' \
    -H 'Referer: https://www.jetbrains.com/toolbox/download/' \
    -H 'Connection: keep-alive' \
    -H 'DNT: 1' \
    --compressed \
  | grep -Po '"linux":.*?[^\\]",' \
  | awk -F ':' '{print $3,":"$4}'| sed 's/[", ]//g')

install -d ${HOME}/bin
curl -sL ${TOOLBOX_URL} | tar xvz --directory=${HOME}/bin --strip-components=1

# node stuff
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash

# INSTALLING GCLOUD THE GOOGLE WAY
# https://cloud.google.com/sdk/docs/downloads-yum
# Need to do `cloud-init` after this is all done

sudo tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
[google-cloud-sdk]
name=Google Cloud SDK
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOM

sudo dnf install google-cloud-sdk -y

# END OF INSTALLING GCLOUD THE GOOGLE WAY

# Poetry for ohmyzsh
# https://python-poetry.org/docs/#enable-tab-completion-for-bash-fish-or-zsh
mkdir $HOME/.oh-my-zsh/custom/plugins/poetry
poetry completions zsh > $HOME/.oh-my-zsh/custom/plugins/poetry/_poetry

# https://github.com/cloudflare/cfssl
# go get -u github.com/cloudflare/cfssl/cmd/...
# go get: github.com/coreos/bbolt@v1.3.2 updating to
# 	github.com/coreos/bbolt@v1.3.5: parsing go.mod:
# 	module declares its path as: go.etcd.io/bbolt
# 	        but was required as: github.com/coreos/bbolt
VERSION=$(curl --silent "https://api.github.com/repos/cloudflare/cfssl/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
VNUMBER=${VERSION#"v"}
wget "https://github.com/cloudflare/cfssl/releases/download/${VERSION}/cfssl_${VNUMBER}_linux_amd64" -O cfssl
chmod +x cfssl
sudo mv cfssl /usr/local/bin
wget "https://github.com/cloudflare/cfssl/releases/download/${VERSION}/cfssljson_${VNUMBER}_linux_amd64" -O cfssljson
chmod +x cfssljson
sudo mv cfssljson /usr/local/bin

# insync
sudo rpm --import https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key

source /etc/os-release
cat << EOF > /tmp/insync.repo
[insync]
name=insync repo
baseurl=http://yum.insync.io/$ID/$VERSION_ID/
gpgcheck=1
gpgkey=https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key
enabled=1
metadata_expire=120m

EOF

sudo mv /tmp/insync.repo /etc/yum.repos.d/insync.repo
sudo dnf update
sudo dnf install insync -y

# docker
sudo dnf -y install dnf-plugins-core
sudo dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
sudo dnf install docker-ce docker-ce-cli containerd.io
sudo systemctl start docker
sudo usermod -aG docker $USER
sudo systemctl enable docker.service
sudo systemctl enable containerd.service

# azure-cli
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
echo -e "[azure-cli]
name=Azure CLI
baseurl=https://packages.microsoft.com/yumrepos/azure-cli
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/azure-cli.repo

sudo dnf install azure-cli
# az login

# 1Password: https://support.1password.com/install-linux/#centos-fedora-or-red-hat-enterprise-linux
sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
sudo dnf install 1password -y

# Github cli
sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo -y
sudo dnf install gh -y
