#!/usr/bin/env bash

set -x

set -e

# homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# https://docs.brew.sh/Homebrew-on-Linux
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile

brew tap orf/brew
brew install git-workspace

brew install awscli
brew install bat
brew install jupyterlab # npm install -g ijavascript; ijsinstall
brew install kubectx
brew install k9s
brew install warrensbox/tap/tfswitch
