#!/usr/bin/env bash

set -x

set -e

# update packages index
sudo pacman --noconfirm -Syu

# yay isn't in pacman for some reason
sudo pacman -S --needed --noconfirm pacaur
pacaur -S --needed --noconfirm yay

while read pkg; do
  yay -S --needed --noconfirm $pkg
done <pkgs
