#!/usr/bin/env bash

set -x

set -e

# update packages index
sudo apt update -y

# Gnome config
# gsettings set org.gnome.desktop.wm.preferences focus-mode 'sloppy'
# gsettings set org.gnome.desktop.wm.preferences auto-raise true

# set hostname if it is not given one during installation
# hostnamectl set-hostname x1

# INSTALLING GCLOUD THE GOOGLE WAY
# https://cloud.google.com/sdk/docs/install#deb
# Need to do `cloud-init` after this is all done

# 1. Add the Cloud SDK distribution URI as a package source:
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# 2. Import the Google Cloud public key:
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

# 3. Update and install the Cloud SDK:
sudo apt-get update && sudo apt-get install -y google-cloud-sdk

# END OF INSTALLING GCLOUD THE GOOGLE WAY

# For KUBECTL
sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update

while read pkg; do
  sudo apt -y install $pkg
done <pkgs

# Installing Snapcraft stuff
sudo snap install authy --beta
sudo snap install bitwarden
sudo snap install code --classic
sudo snap install discord
sudo snap install flameshot
sudo snap install gitkraken --classic
sudo snap install go --classic
sudo snap install kontena-lens --classic
sudo snap install postman
sudo snap install signal-desktop
sudo snap install slack --classic
sudo snap install spotify

sudo snap refresh

# TODO: pip install virtualenvwrapper
# TODO: pip install pgcli
pip3 install kapitan==0.28.0 --user
sudo pip3 install ps_mem
