#!/usr/bin/env bash

set -x

set -e

# Install mega nz file syncyng stuff
source /etc/os-release

# Install minikube, should work for all linux
# https://github.com/kubernetes/minikube/releases
wget -P /tmp https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && sudo install /tmp/minikube-linux-amd64 /usr/local/bin/minikube

# Install Keybase
sudo dnf install https://prerelease.keybase.io/keybase_amd64.rpm -y
run_keybase

# JetBrains Toolbox
# Reference: https://github.com/nagygergo/jetbrains-toolbox-install/blob/master/jetbrains-toolbox.sh
# Note that we grep for linux here, if you are using this on mac/windows please see json output
TOOLBOX_URL=$(curl --silent 'https://data.services.jetbrains.com//products/releases?code=TBA&latest=true&type=release' \
    -H 'Origin: https://www.jetbrains.com' \
    -H 'Accept-Encoding: gzip, deflate, br' \
    -H 'Accept-Language: en-US,en;q=0.8' \
    -H 'Accept: application/json, text/javascript, */*; q=0.01' \
    -H 'Referer: https://www.jetbrains.com/toolbox/download/' \
    -H 'Connection: keep-alive' \
    -H 'DNT: 1' \
    --compressed \
  | grep -Po '"linux":.*?[^\\]",' \
  | awk -F ':' '{print $3,":"$4}'| sed 's/[", ]//g')

install -d ${HOME}/bin
curl -sL ${TOOLBOX_URL} | tar xvz --directory=${HOME}/bin --strip-components=1

# TODO: java openjdk?

# node stuff
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash

# https://github.com/cloudflare/cfssl
# go get -u github.com/cloudflare/cfssl/cmd/...
# go get: github.com/coreos/bbolt@v1.3.2 updating to
# 	github.com/coreos/bbolt@v1.3.5: parsing go.mod:
# 	module declares its path as: go.etcd.io/bbolt
# 	        but was required as: github.com/coreos/bbolt
VERSION=$(curl --silent "https://api.github.com/repos/cloudflare/cfssl/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
VNUMBER=${VERSION#"v"}
wget "https://github.com/cloudflare/cfssl/releases/download/${VERSION}/cfssl_${VNUMBER}_linux_amd64" -O cfssl
chmod +x cfssl
sudo mv cfssl /usr/local/bin
wget "https://github.com/cloudflare/cfssl/releases/download/${VERSION}/cfssljson_${VNUMBER}_linux_amd64" -O cfssljson
chmod +x cfssljson
sudo mv cfssljson /usr/local/bin
