#!/usr/bin/env bash

set -x

set -e

# update packages index
sudo apt update -y

# Gnome config
# gsettings set org.gnome.desktop.wm.preferences focus-mode 'sloppy'
# gsettings set org.gnome.desktop.wm.preferences auto-raise true

# set hostname if it is not given one during installation
# hostnamectl set-hostname x1

# INSTALLING GCLOUD THE GOOGLE WAY
# https://cloud.google.com/sdk/docs/install#deb
# Need to do `cloud-init` after this is all done

# 1. Add the Cloud SDK distribution URI as a package source:
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# 2. Import the Google Cloud public key:
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

# 3. Update and install the Cloud SDK:
sudo apt-get update && sudo apt-get install -y google-cloud-sdk

# END OF INSTALLING GCLOUD THE GOOGLE WAY

# For KUBECTL
sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update

while read pkg; do
  sudo apt -y install $pkg
done <pkgs

# Add key and install repository for VSCode
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

# Installing Snapcraft stuff
sudo snap install code --classic
sudo snap install bitwarden
sudo snap install slack --classic
sudo snap install spotify

python3 -m pip install --upgrade pip
# TODO: pip install virtualenvwrapper
# TODO: pip install pgcli
pip3 install --upgrade kapitan
pip3 install ps_mem

# Install mega nz file syncyng stuff
source /etc/os-release

wget -O /tmp/megasync_amd64.deb https://mega.nz/linux/MEGAsync/xUbuntu${VERSION_ID}/amd64/megasync_4.4.0-1.1_amd64.deb
wget -O /tmp/nautilus-megasync_amd64.deb https://mega.nz/linux/MEGAsync/xUbuntu${VERSION_ID}/amd64/nautilus-megasync_3.6.6_amd64.deb

sudo apt install /tmp/megasync_amd64.deb
sudo apt install /tmp/nautilus-megasync_amd64.deb


# Install minikube, should work for all linux
# https://github.com/kubernetes/minikube/releases
 curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
   && sudo install minikube-linux-amd64 /usr/local/bin/minikube

# Install chrome
wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i /tmp/chrome.deb
# sudo apt -f install

# Install Keybase
wget -O /tmp/keybase_amd64.deb https://prerelease.keybase.io/keybase_amd64.deb
sudo apt install /tmp/keybase_amd64.deb
run_keybase

# TODO: java openjdk?